package edo.mex.gob.repository;

import java.sql.SQLException;
import java.util.List;

public class BatchSqlTables {

    String loginTableSql =
            "CREATE TABLE IF NOT EXISTS public.login(" +
                    "id_login BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                    "user_login VARCHAR," +
                    "password_login VARCHAR," +
                    "created_at TIMESTAMP DEFAULT NOW()," +
                    "updated_at TIMESTAMP," +
                    "deleted BOOLEAN DEFAULT FALSE);";

    String userTableSql =
            "CREATE TABLE IF NOT EXISTS public.user(" +
                    "id_user BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                    "first_name VARCHAR," +
                    "second_first_name VARCHAR," +
                    "last_name VARCHAR," +
                    "second_last_name VARCHAR," +
                    "birth_date TIMESTAMP," +
                    "gender VARCHAR," +
                    "email VARCHAR," +
                    "phone VARCHAR," +
                    "street_name VARCHAR," +
                    "interior_number VARCHAR," +
                    "exterior_number VARCHAR," +
                    "suburb VARCHAR," +
                    "zip_code VARCHAR," +
                    "municipality VARCHAR," +
                    "state_address VARCHAR," +
                    "country VARCHAR," +
                    "created_at TIMESTAMP DEFAULT NOW()," +
                    "updated_at TIMESTAMP," +
                    "deleted BOOLEAN DEFAULT FALSE);";

    String usersLoginSql = "INSERT INTO public.login (user_login, password_login) values('admin', 'admin');";

    String courseTableSql = "CREATE TABLE IF NOT EXISTS public.course(" +
            "id_course BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
            "course_name VARCHAR," +
            "professor VARCHAR," +
            "initial_date TIMESTAMP," +
            "final_date TIMESTAMP," +
            "initial_hour VARCHAR," +
            "final_hour VARCHAR," +
            "course_place VARCHAR," +
            "course_status BOOLEAN," +
            "course_info VARCHAR);";

    String manyToManyTable = "CREATE TABLE IF NOT EXISTS public.users_courses(" +
            "id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
            "user_id INTEGER," +
            "course_id INTEGER," +
            "CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES public.user(id_user)," +
            "CONSTRAINT fk_course FOREIGN KEY(course_id) REFERENCES course(id_course));";

    public BatchSqlTables() throws SQLException {
        List<String> sqlList = List.of(loginTableSql, userTableSql, usersLoginSql, courseTableSql, manyToManyTable);
        new Connector(sqlList);
    }

}
