package edo.mex.gob.repository;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Connector {

    String url = "jdbc:postgresql://localhost:5432/users_manager_db?socketTimeout=30";
    String username = "rappipay";
    String password = "secret";

    String tableSql =
            "CREATE TABLE IF NOT EXISTS public.login(" +
                    "id_login INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                    "user_login VARCHAR," +
                    "password_login VARCHAR," +
                    "created_at TIMESTAMP DEFAULT NOW()," +
                    "updated_at TIMESTAMP," +
                    "deleted BOOLEAN DEFAULT FALSE);";

    public Connector() throws SQLException {
        Connection connection = DriverManager.getConnection(url, username, password);
        Statement stm = connection.createStatement();
        stm.execute(tableSql);
    }

    public static void main(String[] args) throws SQLException {
        Connector con = new Connector();

    }
}
