package edo.mex.gob.repository;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Connector {

    String url = "jdbc:postgresql://localhost:5432/users_manager_db?socketTimeout=30";
    String username = "rappipay";
    String password = "secret";

    String loginTableSql =
            "CREATE TABLE IF NOT EXISTS public.login(" +
                    "id_login INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                    "user_login VARCHAR," +
                    "password_login VARCHAR," +
                    "created_at TIMESTAMP DEFAULT NOW()," +
                    "updated_at TIMESTAMP," +
                    "deleted BOOLEAN DEFAULT FALSE);";

    String userTableSql =
            "CREATE TABLE IF NOT EXISTS public.user(" +
                    "id_user INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                    "first_name VARCHAR," +
                    "first_second_name VARCHAR," +
                    "last_name VARCHAR," +
                    "second_last_name VARCHAR," +
                    "birth_date TIMESTAMP," +
                    "gender VARCHAR," +
                    "email VARCHAR," +
                    "phone VARCHAR," +
                    "street_name VARCHAR," +
                    "interior_number VARCHAR," +
                    "exterior_number VARCHAR," +
                    "suburb VARCHAR," +
                    "zip_code VARCHAR," +
                    "municipality VARCHAR," +
                    "state_address VARCHAR," +
                    "country VARCHAR," +
                    "created_at TIMESTAMP DEFAULT NOW()," +
                    "updated_at TIMESTAMP," +
                    "deleted BOOLEAN DEFAULT FALSE);";

    String usersLoginSql = "INSERT INTO public.login (user_login, password_login) values('admin', 'admin');";

    public Connector() throws SQLException {
        Connection connection = DriverManager.getConnection(url, username, password);
        Statement stm = connection.createStatement();
        stm.addBatch(loginTableSql);
        stm.addBatch(userTableSql);
        stm.addBatch(usersLoginSql);
        stm.executeBatch();
    }

    public static void main(String[] args) throws SQLException {
        Connector con = new Connector();

    }
}
